### ISSUE TITLE
MixIT recipe, pairwise_neg_sisdr

### ISSUE THREAD

**Issue by zmolikova** [asteroid-team/asteroid#594] opened 2022-02-07 15:39 UTC
Hi,
in the MixIT recipe on WHAM, the loss uses `pairwise_neg_sisdr`. It seems to me it should be `multisrc_neg_sisdr` instead. 
https://github.com/asteroid-team/asteroid/blob/fae2f7d1d4eb83da741818a5c375267fe8d98847/egs/wham/MixIT/train.py#L116

Right now, for each mixit partition, each estimate is compared with each reference. This leads to some redundant computation as the permutations are already covered by the mixit partitions. Also, I think it can sometimes even lead to incorrect loss value, because the minimum is taken over each element of the pairwise matrix. That means that for each source, an estimate of different mixit partition can be used (I'm not 100% sure about this).

I can prepare PR but I would be glad if someone confirms this first.

**Comment by mpariente** [comment] 2022-02-07 19:41
I think there is no better person to confirm this than @etzinis, can you have a look please?

**Comment by etzinis** [comment] 2022-02-07 21:12
I agree, after the combinations are extracted, the loss should be computed pairwise.

**Comment by mpariente** [comment] 2022-02-07 22:18
> I agree, after the combinations are extracted, the loss should be computed pairwise.

Do you mean, assuming the sources and estimates are aligned? Or seeking the source/estimate alignment?

**Comment by etzinis** [comment] 2022-02-07 22:52
I mean, assuming that the combinations are fixed (e.g. the mixture of a subset of sources are assigned to mixture 1 and the rest of the to mixture 2), then the loss for each combination should be computed pairwise given the two target mixtures.

**Comment by zmolikova** [comment] 2022-02-08 06:06
I think we're just having different terminology. In Asteroid, "pairwise" refers to computing the loss each-to-each, i.e. for 2 sources and 2 estimates, it returns 2x2 matrix. Here, given the fixed combination, we want to compare the estimates only to the assigned sources (mixtures), that is the `multisrc_neg_sisdr` variant.

**Comment by popcornell** [comment] 2022-02-08 09:35
Yes.  `multisrc_neg_sisdr` is the correct one. Current is incorrect but somehow also works because in the end you care about the min of the losses. Probably we need to add in the mixit loss some dimension checks. 

https://github.com/asteroid-team/asteroid/blob/fae2f7d1d4eb83da741818a5c375267fe8d98847/asteroid/losses/mixit_wrapper.py#L189

**Comment by mpariente** [comment] 2022-02-08 11:30
@zmolikova, it's confirmed :green_circle: Can you make a PR please?

**Closed** 2022-02-09 13:36 UTC
